server:
    port: 8778

debug: true

spring:
    cloud:
        zookeeper:
            connectString: 127.0.0.1:2181
            enabled: false
    sleuth:
        enabled: false

swagger:
    basePackage: com.app.service.controller
    title: ctgpaas-string-spring RESTful APIs
    description: ctgpaas-string-spring RESTful API
    version: 1.0.0-SNAPSHOT
    openApi:
        group: OpenApi
        basePackage: com.app.service.controller
        title: actgpaas-string-spring Open APIs
        description: ctgpaas-string-spring Open API
        version: 1.0.0-SNAPSHOT

logging:
    file: